// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF3VD5VoBjYucXXF3zZm8CQ2d6R1BmPL0',
    appId: '1:941118193655:web:086fcfcc7338b312cd78f2',
    messagingSenderId: '941118193655',
    projectId: 'stockapp-94f18',
    authDomain: 'stockapp-94f18.firebaseapp.com',
    storageBucket: 'stockapp-94f18.firebasestorage.app',
    measurementId: 'G-FKB4V75VB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBet9V_N40ryyU3uIwHVkNBFWPtj329U-4',
    appId: '1:941118193655:android:bf9671c6d7ecfcfecd78f2',
    messagingSenderId: '941118193655',
    projectId: 'stockapp-94f18',
    storageBucket: 'stockapp-94f18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVMm-y77vcmaOHTI5un1T93alIWpX-F9M',
    appId: '1:941118193655:ios:a9945dda0f1d0ba5cd78f2',
    messagingSenderId: '941118193655',
    projectId: 'stockapp-94f18',
    storageBucket: 'stockapp-94f18.firebasestorage.app',
    iosBundleId: 'com.example.stockapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVMm-y77vcmaOHTI5un1T93alIWpX-F9M',
    appId: '1:941118193655:ios:a9945dda0f1d0ba5cd78f2',
    messagingSenderId: '941118193655',
    projectId: 'stockapp-94f18',
    storageBucket: 'stockapp-94f18.firebasestorage.app',
    iosBundleId: 'com.example.stockapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF3VD5VoBjYucXXF3zZm8CQ2d6R1BmPL0',
    appId: '1:941118193655:web:ce73dbc1f8287048cd78f2',
    messagingSenderId: '941118193655',
    projectId: 'stockapp-94f18',
    authDomain: 'stockapp-94f18.firebaseapp.com',
    storageBucket: 'stockapp-94f18.firebasestorage.app',
    measurementId: 'G-8HBQ3K18ZT',
  );
}
